#Info
site_name: AngelaCabeleireira
site_author: PentagonoCabeludo
site_description: Documentação do projeto AngelaCabeleireira, por estudantes da
  disciplina Requisitos de Software, Engenharia de Software, UnB.

#PageTree
nav: 
  - Sobre: index.md
  - Visão do Produto e Projeto:
    - Visão do Produto: VisaoProdutoEProjeto/visaoProduto.md
    - Visão do Projeto: VisaoProdutoEProjeto/visaoProjeto.md
  - Processo de Desenvolvimento de Software: ProcessoDesenv.md
  - Lições Aprendidas: LicoesAprendidas.md
  - Entregas: entregas.md

#Config
docs_dir: docs
theme:
  name: material
  language: pt-BR

  # favicon: img/Icon.svg                 #TODO: descomentar e referenciar o caminho da logo, quando tivermos uma logo para o projeto
  # logo: img/Logo.svg

  features:
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-3
        name: Modo escuro
      primary: white
      accent: red

    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Modo claro
      primary: black

#Repo and extra
repo_url: https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/tree/main
repo_name: AngelaCabeleireira

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/tree/main

markdown_extensions:
  - md_in_html
  - attr_list