#Info
site_name: AngelaCabeleireira
site_author: PentagonoCabeludo
site_description: Documentação do projeto AngelaCabeleireira, por estudantes da
  disciplina Requisitos de Software, Engenharia de Software, UnB.

#PageTree
nav: 
  - Sobre: index.md
  - Visão do Produto: VisaoProdutoEProjeto/visaoProduto.md
  - Visão do Projeto: VisaoProdutoEProjeto/visaoProjeto.md
  - Processo de Desenvolvimento de Software: ProcessoDesenv.md
  - Backlog do Produto: VisaoProdutoEProjeto/backlog.md
  - DoR e DoD: VisaoProdutoEProjeto/dordod.md/
  - Relatórios: Relatorios/relatorios.md
  - Lições Aprendidas: LicoesAprendidas.md
  - Entregas: 
    - Unidade 01: Entregas/unidade01.md
    - Unidade 02: Entregas/unidade02.md
    - Unidade 03: Entregas/unidade03.md

#Config
docs_dir: docs
theme:
  name: material
  language: pt-BR

  favicon: img/icon.svg
  logo: img/logo.png

  features:
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-3
        name: Modo escuro
      primary: white
      accent: red

    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Modo claro
      primary: black

#Repo and extra
repo_url: https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/tree/main
repo_name: AngelaCabeleireira

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/tree/main

markdown_extensions:
  - md_in_html
  - attr_list